### ISSUE TITLE
Not working for me... 

### ISSUE THREAD

**Issue by bloor** [leodr/html-to-jsx-transform#5]
Tauri 1.5
Nuxt 3
Node 18.1

Right after I import the function from the module , it crashes ... 

![image](https://github.com/leodr/html-to-jsx-transform/assets/1420653/8345007c-f679-4b4c-a56a-96dc114b26e7)

**Comment by leodr** [comment]
This was never meant to be ran in a Browser environment (like Tauri) since it uses packages that are only made for Node.js environments. That's what the error is about: It complains that `Buffer is not defined`, which is right, because Buffers only exist in Node.js, but not in the Browser.
