### ISSUE TITLE
Feature request: Change tag names

### ISSUE THREAD

**Issue by Hocdoc** [leodr/html-to-jsx-transform#6]
Thanks for this really helpful project! :-)

I want to use it to generate JSX code but with custom tag names.

F.ex.:

```ts
import { htmlToJsx } from "html-to-jsx-transform";

const jsx = htmlToJsx('<h1 tabindex="0">Hello World!</h1>', 
  {changeTagNames: (id: string) => id === "h1" ? "MyHeaderComponent" : id});

// jsx === '<MyHeaderComponent tabIndex={0}>Hello World!</MyHeaderComponent>';
```

If you are interested I could write a PR for this otherwise I would fork the source.

**Comment by leodr** [comment]
Sounds like a useful addition, feel free to add it.

**Comment by Hocdoc** [comment]
Sorry for my long break. :-(

In the meantime the requirements of our project changed, we don't use html-to-jsx-transform anymore; so I will close this feature request.

But html-to-jsx-transform is still a source of inspiration for us, thanks for your great work!
