### ISSUE TITLE
First line is trimmed, inconsistent with other lines

### ISSUE THREAD

**Issue by bootleq** [leodr/html-to-jsx-transform#7]
Current behavior trims leading whitespace from first input line, while remain lines have spaces preserved.
We can see below test case as example:

https://github.com/leodr/html-to-jsx-transform/blob/0b6942d929df2261161eadf2fa41bf18bee71735/src/html-to-jsx.test.ts#L27-L40

This could result in unexpected indentation, other tools would have to do extra adaption for it.

How about change the behavior to keep spaces untouched?

**Comment by leodr** [comment]
This library is not really concerned with code formatting at all, and I don’t want to get into that to be honest^^ 

I think it’s best you implement this in your own code if you need it. I don’t think this is a simple change like just removing a `.trim()` somewhere, but you can easily count whitespace in your app and add it after calling the `htmlToJsx` function.

I’ll close as not planned, sorry :/
